
/**
 * JAM's JAVA CAFE ORDERING SYSTEM
 * SYSTEM PROJECT IN PROGRAMMING
 * @author Jamaica P. Cavalida BSIT I-1B
 */

/**
 * This class represents MENU where the customer/user
 * can select their preferred coffee/pastries. 
 * This class also let the customer/user to preview
 * their payment.
 * This then calls the Payment() class.
 */

/**
 * The console displays the receipt.
 */


import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class JamsJavaCafe extends javax.swing.JFrame {


    /**
     * Creates new form JamsJavaCafe
     */
    public JamsJavaCafe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitle = new javax.swing.JPanel();
        lblJamsJava = new javax.swing.JLabel();
        drinks = new javax.swing.JPanel();
        radEspresso = new javax.swing.JRadioButton();
        radAmericano = new javax.swing.JRadioButton();
        radCappuccino = new javax.swing.JRadioButton();
        radFlatW = new javax.swing.JRadioButton();
        radMocha = new javax.swing.JRadioButton();
        radHotCh = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkCroissant = new javax.swing.JCheckBox();
        chkCookies = new javax.swing.JCheckBox();
        chkBagels = new javax.swing.JCheckBox();
        chkCinnamon = new javax.swing.JCheckBox();
        subTaxTot = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpSubTotal = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtpTotal = new javax.swing.JTextPane();
        lblSubTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtpTax = new javax.swing.JTextPane();
        lblTax = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        btnPlaceOrd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 153));

        panelTitle.setBackground(new java.awt.Color(0, 153, 153));
        panelTitle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 10, true));
        panelTitle.setForeground(new java.awt.Color(0, 153, 153));

        lblJamsJava.setBackground(new java.awt.Color(0, 204, 153));
        lblJamsJava.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        lblJamsJava.setForeground(new java.awt.Color(255, 255, 255));
        lblJamsJava.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblJamsJava.setText("JAM's JAVA CAFE");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTitleLayout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(lblJamsJava)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTitleLayout.setVerticalGroup(
            panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblJamsJava, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
        );

        drinks.setBackground(new java.awt.Color(0, 204, 204));
        drinks.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 6, true));

        radEspresso.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        radEspresso.setForeground(new java.awt.Color(0, 51, 51));
        radEspresso.setText("Espresso  110.00");
        radEspresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radEspressoActionPerformed(evt);
            }
        });

        radAmericano.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        radAmericano.setForeground(new java.awt.Color(0, 51, 51));
        radAmericano.setText("Americano  125.00");
        radAmericano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radAmericanoActionPerformed(evt);
            }
        });

        radCappuccino.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        radCappuccino.setForeground(new java.awt.Color(0, 51, 51));
        radCappuccino.setText("Cappuccino  155.00");
        radCappuccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radCappuccinoActionPerformed(evt);
            }
        });

        radFlatW.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        radFlatW.setForeground(new java.awt.Color(0, 51, 51));
        radFlatW.setText("Flat White  155.00");
        radFlatW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFlatWActionPerformed(evt);
            }
        });

        radMocha.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        radMocha.setForeground(new java.awt.Color(0, 51, 51));
        radMocha.setText("Mocha  155.00");
        radMocha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radMochaActionPerformed(evt);
            }
        });

        radHotCh.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        radHotCh.setForeground(new java.awt.Color(0, 51, 51));
        radHotCh.setText("Hot Chocolate  155.00");
        radHotCh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radHotChActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 51));
        jLabel2.setText("COFFEE");

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 51));
        jLabel3.setText("PASTRIES");

        chkCroissant.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        chkCroissant.setForeground(new java.awt.Color(0, 51, 51));
        chkCroissant.setText("Croissant  60.00");
        chkCroissant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCroissantActionPerformed(evt);
            }
        });

        chkCookies.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        chkCookies.setForeground(new java.awt.Color(0, 51, 51));
        chkCookies.setText("Cookies  51.00");

        chkBagels.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        chkBagels.setForeground(new java.awt.Color(0, 51, 51));
        chkBagels.setText("Bagels  55.00");
        chkBagels.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBagelsActionPerformed(evt);
            }
        });

        chkCinnamon.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        chkCinnamon.setForeground(new java.awt.Color(0, 51, 51));
        chkCinnamon.setText("Cinnamon Rolls  62.00");
        chkCinnamon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCinnamonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout drinksLayout = new javax.swing.GroupLayout(drinks);
        drinks.setLayout(drinksLayout);
        drinksLayout.setHorizontalGroup(
            drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(drinksLayout.createSequentialGroup()
                        .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radMocha)
                            .addComponent(radHotCh)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, drinksLayout.createSequentialGroup()
                                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radEspresso)
                                    .addComponent(radAmericano)
                                    .addComponent(radCappuccino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkBagels)
                                    .addComponent(chkCookies)
                                    .addComponent(chkCroissant)
                                    .addComponent(chkCinnamon))))
                        .addGap(25, 25, 25))
                    .addGroup(drinksLayout.createSequentialGroup()
                        .addComponent(radFlatW)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(drinksLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(110, 110, 110))
        );
        drinksLayout.setVerticalGroup(
            drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(drinksLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radEspresso, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCroissant))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(drinksLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(radCappuccino, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(drinksLayout.createSequentialGroup()
                        .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radAmericano, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkCookies))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkBagels)))
                .addGap(20, 20, 20)
                .addGroup(drinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radFlatW, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkCinnamon))
                .addGap(22, 22, 22)
                .addComponent(radMocha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(radHotCh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        subTaxTot.setBackground(new java.awt.Color(0, 204, 204));
        subTaxTot.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 153), 6, true));

        txtpSubTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        txtpSubTotal.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        txtpSubTotal.setToolTipText("");
        jScrollPane1.setViewportView(txtpSubTotal);

        txtpTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        txtpTotal.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(txtpTotal);

        lblSubTotal.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        lblSubTotal.setForeground(new java.awt.Color(0, 51, 51));
        lblSubTotal.setText("Subtotal:");

        lblTotal.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(0, 51, 51));
        lblTotal.setText("Total:");

        txtpTax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));
        txtpTax.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        jScrollPane3.setViewportView(txtpTax);

        lblTax.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        lblTax.setForeground(new java.awt.Color(0, 51, 51));
        lblTax.setText("Tax:");

        javax.swing.GroupLayout subTaxTotLayout = new javax.swing.GroupLayout(subTaxTot);
        subTaxTot.setLayout(subTaxTotLayout);
        subTaxTotLayout.setHorizontalGroup(
            subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subTaxTotLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(lblTax, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(46, 46, 46)
                .addGroup(subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        subTaxTotLayout.setVerticalGroup(
            subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subTaxTotLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblSubTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(lblTax, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(subTaxTotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 16)); // NOI18N
        jLabel1.setText("MENU");

        buttonPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 7));

        btnPlaceOrd.setBackground(java.awt.Color.lightGray);
        btnPlaceOrd.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        btnPlaceOrd.setForeground(new java.awt.Color(0, 51, 51));
        btnPlaceOrd.setText("Place Order");
        btnPlaceOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrdActionPerformed(evt);
            }
        });

        btnClear.setBackground(java.awt.Color.lightGray);
        btnClear.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        btnClear.setForeground(new java.awt.Color(0, 51, 51));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnExit.setBackground(java.awt.Color.lightGray);
        btnExit.setFont(new java.awt.Font("Consolas", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 51, 51));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnPlaceOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPlaceOrd)
                    .addComponent(btnClear)
                    .addComponent(btnExit))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subTaxTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(120, 120, 120))
            .addGroup(layout.createSequentialGroup()
                .addGap(351, 351, 351)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(drinks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(subTaxTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrdActionPerformed
        //Place Order Button
       
       DecimalFormat df = new DecimalFormat("0.00"); //2 decimal format
       
       //declaring variables
       double total = 0;
       double subTotal = 0;
       final double taxRate = 0.005;
       double tax = 0;
       
       //Drinks/Coffee section
       if (radEspresso.isSelected()){
           System.out.println("Espresso.................Php 110.00");
           subTotal = subTotal + 110.00;
       } else if(radAmericano.isSelected()){
           System.out.println("Americano................Php 125.00");
           subTotal = subTotal + 125.00;
       } else if(radCappuccino.isSelected()){
           System.out.println("Cappuccino...............Php 155.00");
           subTotal = subTotal + 155.00;
       } else if(radFlatW.isSelected()){
           System.out.println("Flat White...............Php 155.00");
           subTotal = subTotal + 155.00;
       } else if(radMocha.isSelected()){
           System.out.println("Mocha....................Php 155.00");
           subTotal = subTotal + 155.00;
       } else if(radHotCh.isSelected()){
           System.out.println("Hot Chocolate............Php 155.00");
           subTotal = subTotal + 155.00;
       }
       
       
       //Pastries section
       if(chkCroissant.isSelected()){
           subTotal = subTotal + 60.00;
           System.out.println("Croissant................Php 60.00");
       }
       if(chkCookies.isSelected()){
           subTotal = subTotal + 51.00;
           System.out.println("Cookies..................Php 51.00");          
       }
       if(chkBagels.isSelected()){
           subTotal = subTotal + 55.00;
           System.out.println("Bagels...................Php 55.00");
       }
       if(chkCinnamon.isSelected()){
           subTotal = subTotal + 62.00;
           System.out.println("Cinnamon Rolls...........Php 62.00");
       }
        
       
       txtpSubTotal.setText(Double.toString(subTotal));
       
       //declaring/assigning variables
        subTotal = Double.parseDouble(txtpSubTotal.getText());
        tax = subTotal * taxRate;
        total = tax + subTotal;
        
        
       //getting inputs
       txtpTax.setText(Double.toString(tax));
       txtpTotal.setText(Double.toString(total));
       
       txtpSubTotal.setText(df.format(subTotal));
       txtpTax.setText(df.format(tax));
       txtpTotal.setText(df.format(total));
       
       //displaying stuff like total, tax, entered cash, and balance
       System.out.println();
       System.out.println("Tax......................0.003");
       System.out.println("TOTAL....................Php " + total);
       
       
       //this calls the next window or class
       new Payment(subTotal, tax).setVisible(true);
      

    }//GEN-LAST:event_btnPlaceOrdActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // Cancel Button 
        // Exits and/or cancels order
        
        System.out.println("Exited & Cancelled");
        System.exit(0);
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void radEspressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radEspressoActionPerformed
        // selects Espresso
        if(radEspresso.isSelected()){
            radAmericano.setSelected(false);
            radCappuccino.setSelected(false);
            radFlatW.setSelected(false);
            radMocha.setSelected(false);
            radHotCh.setSelected(false);
        }
    }//GEN-LAST:event_radEspressoActionPerformed

    private void radAmericanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radAmericanoActionPerformed
        // selects Americano
        if(radAmericano.isSelected()){
            radEspresso.setSelected(false);
            radCappuccino.setSelected(false);
            radFlatW.setSelected(false);
            radMocha.setSelected(false);
            radHotCh.setSelected(false);
        }
    }//GEN-LAST:event_radAmericanoActionPerformed

    private void radCappuccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radCappuccinoActionPerformed
        // selects Cappuccino
        if(radCappuccino.isSelected()){
            radEspresso.setSelected(false);
            radAmericano.setSelected(false);
            radFlatW.setSelected(false);
            radMocha.setSelected(false);
            radHotCh.setSelected(false);
        }
    }//GEN-LAST:event_radCappuccinoActionPerformed

    private void radFlatWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFlatWActionPerformed
        // selects Flat White
        if(radFlatW.isSelected()){
            radEspresso.setSelected(false);
            radAmericano.setSelected(false);
            radCappuccino.setSelected(false);
            radMocha.setSelected(false);
            radHotCh.setSelected(false);
        }
    }//GEN-LAST:event_radFlatWActionPerformed

    private void radMochaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radMochaActionPerformed
        // selects Mocha
        if(radMocha.isSelected()){
            radEspresso.setSelected(false);
            radAmericano.setSelected(false);
            radCappuccino.setSelected(false);
            radFlatW.setSelected(false);
            radHotCh.setSelected(false);
        }
    }//GEN-LAST:event_radMochaActionPerformed

    private void radHotChActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radHotChActionPerformed
        // selects Hot Chocolate
        if(radHotCh.isSelected()){
            radEspresso.setSelected(false);
            radAmericano.setSelected(false);
            radCappuccino.setSelected(false);
            radFlatW.setSelected(false);
            radMocha.setSelected(false);
        }
    }//GEN-LAST:event_radHotChActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        //button for reset
        // clears all selected
        
        radEspresso.setSelected(false);
        radAmericano.setSelected(false);
        radCappuccino.setSelected(false);
        radFlatW.setSelected(false);
        radMocha.setSelected(false);
        radHotCh.setSelected(false);
        chkCroissant.setSelected(false);
        chkCookies.setSelected(false);
        chkBagels.setSelected(false);
        chkCinnamon.setSelected(false);
        txtpSubTotal.setText("");
        txtpTax.setText("");
        txtpTotal.setText("");


    }//GEN-LAST:event_btnClearActionPerformed

    private void chkCinnamonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCinnamonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCinnamonActionPerformed

    private void chkCroissantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCroissantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkCroissantActionPerformed

    private void chkBagelsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBagelsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBagelsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JamsJavaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JamsJavaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JamsJavaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JamsJavaCafe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //a signature display of Jam's Java Cafe Ordering System
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd, EEEE h:mm a");
        LocalDateTime now = LocalDateTime.now();
        System.out.println();
        System.out.println("--------------------------------------\n");
        System.out.println(
                "******" +
                "\t" + "JAM's JAVA CAFE" +
                "  ******" + "\n" +
                "Address: Samboan, Cebu, Philippines" + "\n" +
                "Email: jamsJavaCafe@gmail.com" + "\n" +
                "Time: " + (dtf.format(now)) + "\n" +
                "********************************\n"
                );
        
        

        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new JamsJavaCafe().setVisible(true);
                this.setLocationRelativeTo(null);

            }

            private void setLocationRelativeTo(Object object) {
                //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnPlaceOrd;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JCheckBox chkBagels;
    private javax.swing.JCheckBox chkCinnamon;
    private javax.swing.JCheckBox chkCookies;
    private javax.swing.JCheckBox chkCroissant;
    private javax.swing.JPanel drinks;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblJamsJava;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTax;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JRadioButton radAmericano;
    private javax.swing.JRadioButton radCappuccino;
    private javax.swing.JRadioButton radEspresso;
    private javax.swing.JRadioButton radFlatW;
    private javax.swing.JRadioButton radHotCh;
    private javax.swing.JRadioButton radMocha;
    private javax.swing.JPanel subTaxTot;
    private javax.swing.JTextPane txtpSubTotal;
    private javax.swing.JTextPane txtpTax;
    private javax.swing.JTextPane txtpTotal;
    // End of variables declaration//GEN-END:variables
   }
