
/**
 * This is the Payment() class where the customer/user
 * can input their cash to be calculated and to
 * display the balance/change.
 * This is the last class that should be executed by the user.
 */

/**
 * The console displays the receipt.
 */


import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.text.DecimalFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

public class Payment extends javax.swing.JFrame implements ActionListener{
    
    /**
     * Creates new form Payment
     */
    
    double total, subTotal1, tax1;

    public Payment() {
        initComponents();
        this.setLocationRelativeTo(null);
        

    }

    Payment(double subTotal, double tax) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        initComponents();
        this.setLocationRelativeTo(null);
        
        //declaring variables
        subTotal1 = subTotal; tax1 = tax;
        total = subTotal1 + tax1;
        txtFTotalPay.setText("" + total);
        
        
        //a signature display of Jam's Java Cafe Ordering System
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd, EEEE h:mm a");
        LocalDateTime now = LocalDateTime.now();
        
        txtAreaHeader.setText(
                "\t" + "JAM's JAVA CAFE" + "\n\n" +
                "Address: Cebu, Philippines" + "\n" +
                "Email: jamsJavaCafe@gmail.com" + "\n" +
                "Time: " + (dtf.format(now))
                );
    }

    
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFTotalPay = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFCash = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFChange = new javax.swing.JTextField();
        btnOK = new javax.swing.JButton();
        lblEnterCash = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaHeader = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 3));

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel1.setText("TOTAL:");

        txtFTotalPay.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        txtFTotalPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFTotalPayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel2.setText("CASH:");

        txtFCash.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        txtFCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFCashActionPerformed(evt);
            }
        });
        txtFCash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFCashKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        jLabel3.setText("CHANGE:");

        txtFChange.setFont(new java.awt.Font("Consolas", 1, 15)); // NOI18N
        txtFChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFChangeActionPerformed(evt);
            }
        });

        btnOK.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        lblEnterCash.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        lblEnterCash.setText("Enter your cash here:");

        txtAreaHeader.setEditable(false);
        txtAreaHeader.setBackground(new java.awt.Color(0, 204, 204));
        txtAreaHeader.setColumns(20);
        txtAreaHeader.setFont(new java.awt.Font("Comic Sans MS", 1, 13)); // NOI18N
        txtAreaHeader.setRows(5);
        jScrollPane1.setViewportView(txtAreaHeader);

        btnCancel.setFont(new java.awt.Font("Consolas", 0, 15)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterCash)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtFChange, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFCash, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                            .addComponent(txtFTotalPay))))
                .addGap(150, 150, 150))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93)
                        .addComponent(btnCancel)
                        .addGap(44, 44, 44))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFTotalPay, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(lblEnterCash)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFCash, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(txtFChange, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49))))
        );

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 0, 16)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PAYMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFTotalPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFTotalPayActionPerformed
        
        //total will be visible for the next window
        new JamsJavaCafe().setVisible(true); 
        
        //decimal format
        DecimalFormat df = new DecimalFormat("0.00"); 
        txtFTotalPay.setText(Double.toString(total));
        txtFTotalPay.setText("" + df.format(total));
        
            
    }//GEN-LAST:event_txtFTotalPayActionPerformed
  
    
    private void txtFChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFChangeActionPerformed
        // implementing decimal format:
        double finalTotal = 0;
        DecimalFormat df = new DecimalFormat("0.00");
        txtFChange.setText("" + df.format(finalTotal));
    }//GEN-LAST:event_txtFChangeActionPerformed
    
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        //Ok button
        String content = txtFCash.getText();
        if (content.equals("")) {
            
            lblEnterCash.setToolTipText("Enter your cash here: ");
            JOptionPane.showMessageDialog(null, "Please enter cash.");
            
        } else{
        
            //signature display when on the receipt/console when order is confirmed
        JOptionPane.showMessageDialog(null, "Confirmed!" + "\n" +
                    "Ordered Successfully!" + "\n" +
                    "Thank You.");
        System.out.println("\n\n***********************************");
        System.out.println("\tTHANK YOU! Come again!");
        System.out.println("***********************************\n");
        
        System.out.println("--------------------------------------\n");
        System.out.println("\n\nOrder Confirmed");
        }
        
    }//GEN-LAST:event_btnOKActionPerformed
    
    private void txtFCashKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFCashKeyPressed
        
        DecimalFormat df = new DecimalFormat("0.00");  //decimal format
        
        
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            // entered cash is enough
            //Scanner pay = new Scanner(System.in);
            double cash = Double.parseDouble(txtFCash.getText());

        
        if(total <= cash){
            System.out.print("Cash.....................Php " + cash);
            
            //calculates and diplays the change
            double finalTotal = cash - total;
            txtFChange.setText("" + df.format(finalTotal));
            System.out.print("\nBalance..................Php " + df.format(finalTotal) + "\n");
        }else {
            
            //displays when entered cash is not enough
            JOptionPane.showMessageDialog(null, "Insufficient!");
        } 
        }
    }//GEN-LAST:event_txtFCashKeyPressed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        //cancel button
        
        System.out.println("\n\nCancelled"); 
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtFCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFCashActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtFCashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //a signature display of Jam's Java Cafe Ordering System in the console
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd, EEEE h:mm a");
        LocalDateTime now = LocalDateTime.now();
        System.out.println();
        System.out.println("--------------------------------------\n");
        System.out.println(
                "******" +
                "\t" + "JAM's JAVA CAFE" +
                "  ******" + "\n" +
                "Address: Samboan, Cebu, Philippines" + "\n" +
                "Email: jamsJavaCafe@gmail.com" + "\n" +
                "Time: " + (dtf.format(now)) + "\n" +
                "********************************\n"
                );
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
                new JamsJavaCafe().setVisible(true);
            }
           
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblEnterCash;
    private javax.swing.JTextArea txtAreaHeader;
    private javax.swing.JTextField txtFCash;
    private javax.swing.JTextField txtFChange;
    private javax.swing.JTextField txtFTotalPay;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

        
    


}
